AWSTemplateFormatVersion: '2010-09-09'
Transform: "AWS::Serverless-2016-10-31"
Description: "Decode Barcodes and QR codes with AWS Lambda"

Parameters:
  BucketName:
    Description: Name of the bucket
    Type: String

Resources:
  #AWS Lambda Function
  PillowLayer:
    Type: "AWS::Lambda::LayerVersion"
    Properties:
      CompatibleRuntimes:
        - python3.7
      Content:
        S3Bucket: !Ref BucketName
        S3Key: "BarcodeQRDecoder/qr-reader/assets/pillow_layer.zip"
      LayerName: "PillowLayer"

  PyzbarLayer:
    Type: "AWS::Lambda::LayerVersion"
    Properties:
      CompatibleRuntimes:
        - python3.7
      Content:
        S3Bucket: !Ref BucketName
        S3Key: "BarcodeQRDecoder/qr-reader/assets/pyzbar_layer.zip"
      LayerName: "PyzbarLayer"

  DecoderLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [ {
          "Effect": "Allow",
          "Principal": {
            "Service": [ "lambda.amazonaws.com" ]
          },
          "Action": [ "sts:AssumeRole" ]
        } ]
      }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

      RoleName: "DecoderLambdaRole"

  DecoderLambda:
    Type: AWS::Serverless::Function
    DependsOn: DecoderLambdaRole
    Properties:
      FunctionName: "Decoder-Function"
      CodeUri: 
        Bucket: !Ref BucketName
        Key: "BarcodeQRDecoder/qr-reader/assets/lambda_function.zip"
      Handler: "lambda_function.lambda_handler"
      Runtime: "python3.7"
      Timeout: 60
      Role:
        Fn::GetAtt:
          - DecoderLambdaRole
          - Arn
      Layers:
        - !Ref PillowLayer
        - !Ref PyzbarLayer